# https://taskfile.dev

version: '3'

silent: true
dotenv: ['.env']

tasks:
  dev:
    cmds:
      - poetry run uvicorn main:app --reload --port "$PORT"
  prod:run:
    cmds:
      - poetry run gunicorn -c gunicorn.conf.py main:app
  prod:kill:
    cmds:
      - kill `cat prod.pid`
  test: 
    cmds:
      - poetry run pytest